"on":
  push:
    branches:
    - master
name: Deploy to Porter
jobs:
  porter-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2.3.4
    - name: Docker build, push
      id: docker_build_push
      run: |2

        export $(echo "${{secrets.ENV_TRAIN_TYPICAL_FORGET}}" | xargs)
        echo "${{secrets.ENV_TRAIN_TYPICAL_FORGET}}" > ./env_porter
        echo "uhoh"
        cat ./env_porter
        sudo add-apt-repository ppa:cncf-buildpacks/pack-cli
        sudo apt-get update
        sudo apt-get install pack-cli
        sudo pack build 975032674314.dkr.ecr.eu-west-3.amazonaws.com/train-typical-forget-default:$(git rev-parse --short HEAD) --path ./ --builder heroku/buildpacks:18 --env-file ./env_porter
        sudo docker push 975032674314.dkr.ecr.eu-west-3.amazonaws.com/train-typical-forget-default:$(git rev-parse --short HEAD)
    - name: Deploy on Porter
      id: deploy_porter
      run: |2

        curl -X POST "https://dashboard.getporter.dev/api/webhooks/deploy/${{secrets.WEBHOOK_TRAIN_TYPICAL_FORGET}}?commit=$(git rev-parse --short HEAD)&repository=975032674314.dkr.ecr.eu-west-3.amazonaws.com/train-typical-forget-default"
