"on":
  workflow_dispatch:
    inputs:
      pr_branch_from:
        description: Pull request head branch
        required: true
        type: string
      pr_branch_into:
        description: Pull request base branch
        required: true
        type: string
      pr_number:
        description: Pull request number
        required: true
        type: string
      pr_title:
        description: Pull request title
        required: true
        type: string
name: Porter Preview Environment
jobs:
  porter-preview:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2.3.4
    - name: Create Porter preview env
      timeout-minutes: 30
      uses: porter-dev/porter-preview-action@v0.2.1
      with:
        action_id: ${{ github.run_id }}
        cluster: "1"
        host: https://5c24-131-239-192-194.ngrok.io
        installation_id: "30668812"
        namespace: pr-${{ github.event.inputs.pr_number }}-js-test-app
        pr_branch_from: ${{ github.event.inputs.pr_branch_from }}
        pr_branch_into: ${{ github.event.inputs.pr_branch_into }}
        pr_id: ${{ github.event.inputs.pr_number }}
        pr_name: ${{ github.event.inputs.pr_title }}
        project: "1"
        repo_name: js-test-app
        repo_owner: portersupport
        token: ${{ secrets.PORTER_PREVIEW_1_1 }}
    concurrency:
      group: ${{ github.workflow }}-${{ github.event.inputs.pr_number }}
