"on":
  push:
    branches:
    - master
name: Deploy to test
jobs:
  porter-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set Github tag
      id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    - name: Deploy stack
      timeout-minutes: 30
      uses: porter-dev/porter-cli-action@v0.1.0
      with:
        command: apply -f porter.yaml
      env:
        PORTER_CLUSTER: "1"
        PORTER_HOST: https://feasible-horse-manually.ngrok-free.app
        PORTER_PR_NUMBER: ${{ github.event.number }}
        PORTER_PROJECT: "1"
        PORTER_STACK_NAME: test
        PORTER_TAG: ${{ steps.vars.outputs.sha_short }}
        PORTER_TOKEN: ${{ secrets.PORTER_STACK_1_1 }}
        DOCKER_BUILDKIT: "1"
        PORTER_BUILDKIT_ARGS: --cache-to type=gha --cache-from type=gha
