"on":
  push:
    branches:
    - master
name: Deploy to Porter
jobs:
  porter-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2.3.4
    - name: Update Porter App
      timeout-minutes: 20
      uses: porter-dev/porter-update-action@v0.1.0
      with:
        app: idk
        cluster: "9"
        host: https://dashboard.dev.getporter.dev
        project: "8"
        token: ${{ secrets.PORTER_TOKEN_8 }}
