on:
  push:
    branches:
      - master
name: Deploy to Porter
jobs:
  porter-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set Github tag
      id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    - name: Deploy Stack
      timeout-minutes: 20
      uses: porter-dev/porter-cli-action@v0.1.0
      with:
        command: apply -f porter-stack.yaml
      env:
        PORTER_HOST: https://dashboard.getporter.dev
        PORTER_CLUSTER: 2489
        PORTER_PROJECT: 6680
        PORTER_TOKEN: ${{ secrets.TEST_TOKEN }}
        PORTER_TAG: ${{ steps.vars.outputs.sha_short }}
        PORTER_STACK_NAME: new-stack
