"on":
  push:
    branches:
    - master
name: Deploy to Porter
jobs:
  porter-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4

      - name: Set Github tag
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Update the Porter deployment
        timeout-minutes: 20
        uses: porter-dev/porter-update-action@v0.1.0
        with:
          app: porter-performance-test
          cluster: 1118
          project: 777
          namespace: kube-public
          token: ${{ secrets.PORTER_TOKEN_777 }}
          dockerfile: ./docDockerfile
          tag: ${{ steps.vars.outputs.sha_short }}
